---
# tasks file for ansible-git-role

- name: Ansible Git | Set working directory
  ansible.builtin.set_fact:
    working_dir: "{{ git_working_dir | default(ansible_env.HOME) }}"
    git_repo_name: "{{ git_repo_url | regex_findall('[^\/]*.git$') | replace('.git','') }}"

- name: Ansible Git | Extract repo name
  ansible.builtin.set_fact:
    git_repo: "{{ git_repo_name | join(' ') }}"

- name: Ansible Git | Clone repository
  ansible.builtin.git:
    repo: "{{ (git_repo_url | replace(protocol, protocol_token)) if git_token is defined and git_token != '' else git_repo_url }}"
    version: "{{ git_branch | default('main', true) }}"
    dest: "{{ working_dir }}/{{ git_repo }}"
  vars:
    protocol: "https://"
    protocol_token: "https://{{ git_token | default(omit,true) }}@"
  when: git_action == 'clone'

- name: Ansible Git | Prepare for commit and push
  when: git_action == 'push'
  block:
    - name: Ansible Git | Configure local repo to commit and push
      ansible.builtin.shell:
        chdir: "{{ working_dir }}/{{ git_repo }}"
        cmd: |
          git config --local user.name {{ git_user }}
          git config --local user.email {{ git_email }}

    - name: Ansible Git | Add files to staged changes
      ansible.builtin.shell:
        cmd: git add -A
        chdir: "{{ working_dir }}/{{ git_repo }}"
      register: git_add_result

    - name: Ansible Git | Commit changes
      ansible.builtin.shell:
        cmd: git commit -m "{{ git_commit_message }}"
        chdir: "{{ working_dir }}/{{ git_repo }}"
      register: git_commit_result

    - name: Ansible Git | Push changes to remote repo
      ansible.builtin.shell:
        cmd: git push -u origin {{ git_branch | default('main', true) }}
        chdir: "{{ working_dir }}/{{ git_repo }}"
      register: git_push_result
